In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/transactions.csv")

print("Dataset Loaded Successfully!")
print(df.shape)

Dataset Loaded Successfully!
(250000, 17)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction id      250000 non-null  str
 1   timestamp           250000 non-null  str
 2   transaction type    250000 non-null  str
 3   merchant_category   250000 non-null  str
 4   amount (INR)        250000 non-null  int64
 5   transaction_status  250000 non-null  str
 6   sender_age_group    250000 non-null  str
 7   receiver_age_group  250000 non-null  str
 8   sender_state        250000 non-null  str
 9   sender_bank         250000 non-null  str
 10  receiver_bank       250000 non-null  str
 11  device_type         250000 non-null  str
 12  network_type        250000 non-null  str
 13  fraud_flag          250000 non-null  int64
 14  hour_of_day         250000 non-null  int64
 15  day_of_week         250000 non-null  str
 16  is_weekend          250000 non-null  int64
dtypes: int64(4), str(13)
memory usage: 32.4 MB

In [4]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

In [5]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Missing Values:
transaction id        0
timestamp             0
transaction type      0
merchant_category     0
amount (INR)          0
transaction_status    0
sender_age_group      0
receiver_age_group    0
sender_state          0
sender_bank           0
receiver_bank         0
device_type           0
network_type          0
fraud_flag            0
hour_of_day           0
day_of_week           0
is_weekend            0
dtype: int64

Duplicate Rows:
0

In [6]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

df['month'] = df['timestamp'].dt.month_name()

df['quarter'] = df['timestamp'].dt.quarter

df['year'] = df['timestamp'].dt.year

df[['timestamp', 'month', 'quarter', 'year']].head()

            timestamp    month  quarter  year
0 2024-10-08 15:17:28  October        4  2024
1 2024-04-11 06:56:00    April        2  2024
2 2024-04-02 13:27:18    April        2  2024
3 2024-01-07 10:09:17  January        1  2024
4 2024-01-23 19:04:23  January        1  2024

In [ ]:
df['high_value_transaction'] = np.where(df['amount (INR)'] > 5000, 1, 0)
df[['amount (INR)', 'high_value_transaction']].head()

high_value_transaction
0    239044
1     10956
Name: count, dtype: int64

In [9]:
df['transaction_status'].value_counts()

transaction_status
SUCCESS    237624
FAILED      12376
Name: count, dtype: int64

In [10]:
df['fraud_flag'].value_counts()

fraud_flag
0    249520
1       480
Name: count, dtype: int64

In [11]:
df.groupby('merchant_category')['amount (INR)'].sum().sort_values(ascending=False)

merchant_category
Shopping         76863207
Grocery          58277893
Utilities        52742482
Fuel             38982575
Education        38704346
Other            21073449
Food             19919402
Entertainment     8309080
Healthcare        6874159
Transport         6192416
Name: amount (INR), dtype: int64

In [12]:
monthly_trend = df.groupby('month')['amount (INR)'].sum()

monthly_trend

month
April        26988791
August       27845907
December     27311087
February     25826330
January      27456691
July         28079905
June         27032118
March        27508202
May          28024857
November     26892531
October      27866829
September    27105761
Name: amount (INR), dtype: int64

In [13]:
monthly_trend = df.groupby(
    pd.Categorical(
        df['month'],
        categories=[
            'January','February','March','April','May','June',
            'July','August','September','October','November','December'
        ],
        ordered=True
    )
)['amount (INR)'].sum()

monthly_trend

January      27456691
February     25826330
March        27508202
April        26988791
May          28024857
June         27032118
July         28079905
August       27845907
September    27105761
October      27866829
November     26892531
December     27311087
Name: amount (INR), dtype: int64

In [14]:
fraud_by_category = df[df['fraud_flag'] == 1].groupby(
    'merchant_category'
)['fraud_flag'].count().sort_values(ascending=False)

fraud_by_category

merchant_category
Grocery          94
Food             73
Shopping         62
Other            50
Fuel             48
Transport        43
Entertainment    40
Utilities        33
Healthcare       21
Education        16
Name: fraud_flag, dtype: int64

In [15]:
fraud_by_bank = df[df['fraud_flag'] == 1].groupby(
    'sender_bank'
)['fraud_flag'].count().sort_values(ascending=False)

fraud_by_bank

sender_bank
SBI         109
ICICI        66
HDFC         62
IndusInd     52
PNB          52
Kotak        50
Axis         49
Yes Bank     40
Name: fraud_flag, dtype: int64

In [16]:
fraud_by_state = df[df['fraud_flag'] == 1].groupby(
    'sender_state'
)['fraud_flag'].count().sort_values(ascending=False)

fraud_by_state

sender_state
Maharashtra       71
Karnataka         69
Uttar Pradesh     52
Delhi             50
Rajasthan         46
Gujarat           43
Tamil Nadu        40
Telangana         39
Andhra Pradesh    35
West Bengal       35
Name: fraud_flag, dtype: int64

In [17]:
df['high_value_transaction'].value_counts()

high_value_transaction
0    239044
1     10956
Name: count, dtype: int64

In [18]:
df.to_csv('../data/cleaned/transactions_cleaned.csv', index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!